[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opentelemetry-sitecustomize"
dynamic = ["version"]
description = "OpenTelemetry auto-instrumentation for Python applications using sitecustomize"
readme = "README.md"
license = "Apache-2.0"
authors = [
    { name = "Lukas Hering", email = "lukasheringb@gmail.com" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: OpenTelemetry",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
requires-python = ">=3.9"
dependencies = [
    "sitecustomize-entrypoints ~= 1.0",
    "opentelemetry-api>=1.25",
    "opentelemetry-instrumentation>=0.46b0",
]

[project.urls]
Homepage = "https://github.com/herin049/opentelemetry-sitecustomize"

[tool.hatch.version]
path = "src/opentelemetry/instrumentation/sitecustomize/version.py"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
]

[tool.hatch.build.targets.wheel]
packages = ["src/opentelemetry"]

[project.entry-points.sitecustomize]
opentelemetry-sitecustomize = "opentelemetry.instrumentation.auto_instrumentation:initialize"
